#!/bin/sh

#export JAVA_HOME=/usr/local/java
#PATH=/usr/local/java/bin:${PATH}

cd /target

#---------------------------------#
# dynamically build the classpath #
#---------------------------------#
THE_CLASSPATH=
for i in `ls ./lib/*.jar`
do
  THE_CLASSPATH=${THE_CLASSPATH}:${i}
done

#---------------------------#
# run the anti-spam program #
#---------------------------#
java -cp ".:${THE_CLASSPATH}"  \
  jar embedded-jetty-jsp-1-SNAPSHOT.jar