#!/bin/sh

cd /opt/Deploya

#---------------------------------#
# dynamically build the classpath #
#---------------------------------#
THE_CLASSPATH=
for i in `ls ./lib/*.jar`
do
  THE_CLASSPATH=${THE_CLASSPATH}:${i}
done

THE_CLASSPATH=${THE_CLASSPATH}:./config/*

java -cp ".:${THE_CLASSPATH}"  \
  com.varentech.deploya.Main